import streamlit as st
import pandas as pd
import plotly.graph_objects as go

from src.anomaly_detection import detect_anomalies
from src.recommendations import get_recommendations
from src.prediction import predict_battery_threshold
from src.prediction import get_battery_prediction_series

# ---------------------------------------------------------
# Load the telemetry generated by data_generator.py
# ---------------------------------------------------------
df = pd.read_csv("data/telemetry.csv")

# Convert timestamp from a string into a proper Pandas datetime object.
# This datetime object lets us do things like df["timestamp"].dt.hour
# This is important because we'll use it as the x-axis of our time-series plots.
df["timestamp"] = pd.to_datetime(df["timestamp"])


# Run anomaly detection on the latest telemetry.
anomalies = detect_anomalies(df)

# Generate actions based on the detected anomalies.
recommendations = get_recommendations(anomalies)

# Predict when battery will reach the critical threshold.
battery_prediction = predict_battery_threshold(df)
battery_forecast = get_battery_prediction_series(df)

st.title("ANTELLAY Mission Intelligence")

st.subheader("Data Quality")

missing_values = df.isna().sum().sum()

if missing_values == 0:
    st.success("Telemetry data quality: Good — no missing values detected.")
else:
    st.warning(
        f"Telemetry data contains {missing_values} missing values."
    )

st.header("Mission Status")

if any(anomaly["severity"] == "CRITICAL" for anomaly in anomalies):
    st.error("🔴 CRITICAL — Immediate attention required")

elif any(anomaly["severity"] == "WARNING" for anomaly in anomalies):
    st.warning("🟡 WARNING — System requires monitoring")

else:
    st.success("🟢 NORMAL — No active anomalies detected")

with st.expander("View Raw Telemetry"):
    st.dataframe(df)

st.subheader("Latest Telemetry")

latest = df.iloc[-1]

col1, col2, col3, col4, col5 = st.columns(5)

col1.metric(
    "Temperature",
    f"{latest['temperature']:.1f} °C"
)

col2.metric(
    "Battery",
    f"{latest['battery']:.1f} %"
)

col3.metric(
    "Signal",
    f"{latest['signal_strength']:.1f} dBm"
)

col4.metric(
    "Altitude",
    f"{latest['altitude']:.2f} km"
)

col5.metric(
    "CPU Load",
    f"{latest['cpu_load']:.1f} %"
)

st.header("Telemetry Trends")

col1, col2 = st.columns(2)

with col1:
    st.subheader("Thermal Telemetry")
    st.line_chart(
        df.set_index("timestamp")["temperature"]
    )

with col2:
    st.subheader("Power Telemetry")
    st.line_chart(
        df.set_index("timestamp")["battery"]
    )

col1, col2 = st.columns(2)

with col1:
    st.subheader("Communication Telemetry")
    st.line_chart(
        df.set_index("timestamp")["signal_strength"]
    )

with col2:
    st.subheader("Orbital Telemetry")
    st.line_chart(
        df.set_index("timestamp")["altitude"]
    )

st.subheader("Onboard Computing")
st.line_chart(
    df.set_index("timestamp")["cpu_load"]
)


st.header("Anomaly Detection")
if not anomalies:
    st.success("🟢 No active anomalies detected.")
else:
    for anomaly in anomalies:
        severity = anomaly["severity"]
        code = anomaly["code"]
        message = anomaly["message"]

        if severity == "CRITICAL":
            st.error(
                f"🔴 {severity} | {code}\n\n"
                f"{message}"
            )
        else:
            st.warning(
                f"🟡 {severity} | {code}\n\n"
                f"{message}"
            )


st.header("Battery Prediction")

if battery_prediction["minutes_remaining"] is None:

    st.info(
        "Battery is not currently showing a declining trend. "
        "A threshold-crossing prediction is unavailable."
    )

else:
    # Forecast slightly beyond the predicted critical threshold crossing.
    forecast_minutes = int(battery_prediction["minutes_remaining"]) + 60

    battery_forecast = get_battery_prediction_series(
        df,
        forecast_minutes=forecast_minutes
    )

    col1, col2 = st.columns(2)

    with col1:
        st.metric(
            "Current Battery",
            f'{battery_prediction["current_battery"]:.1f}%'
        )

    with col2:
        st.metric(
            "Estimated Time to 40%",
            battery_prediction["time_remaining"]
        )

    st.caption(
        f'Estimated degradation rate: '
        f'{battery_prediction["slope"]:.3f} percentage points/min'
    )
    fig = go.Figure()

    # Actual battery telemetry
    fig.add_trace(
        go.Scatter(
            x=df["timestamp"],
            y=df["battery"],
            mode="lines",
            name="Actual Battery"
        )
    )

    # Predicted future battery
    fig.add_trace(
        go.Scatter(
            x=pd.date_range(
                start=df["timestamp"].iloc[-1],
                periods=len(battery_forecast),
                freq="min"
            ),
            y=battery_forecast["predicted_battery"],
            mode="lines",
            name="Predicted Battery",
            line=dict(dash="dash")
        )
    )

    # Critical battery threshold
    fig.add_hline(
        y=battery_prediction["threshold"],
        line_dash="dot",
        annotation_text="Critical Threshold (40%)"
    )

    fig.update_layout(
        xaxis_title="Time",
        yaxis_title="Battery (%)",
        yaxis=dict(
            range=[0, 100]
        ),
        hovermode="x unified"
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )


st.header("Recommended Actions")
if not recommendations:
    st.success("🟢 No action required.")
else:
    for recommendation in recommendations:
        severity = recommendation["severity"]
        code = recommendation["code"]
        action = recommendation["action"]

        if severity == "CRITICAL":
            st.error(
                f"🔴 {severity} | {code}\n\n"
                f"Recommended Action: {action}"
            )

        else:
            st.warning(
                f"🟡 {severity} | {code}\n\n"
                f"Recommended Action: {action}"
            )
